name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight UTC

  workflow_dispatch:  # Allows manual execution

jobs:
  generate:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: RickMelendez
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit & Push Snake Animation
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Updated Snake contribution graph"
          git push origin output
